### ISSUE TITLE
Please add icons

### ISSUE THREAD

**Issue by dirn-intg** [SethStormR/GreyStone#1]
Hi please add icons for the apps below

1. cooler control
2. deadbeef
3. dosbox
4. easy effects
5. electron
6. gzdoom
7. htop
8. kate
9. konversation
10. ms teams
11. notepadqq
12. postman
13. stacer
14. skype
15. super tux kart
16. telegram
17. timeshift
18. qbittorent
19. ventoy
20. virtualbox
21. world of padman
22. webcamoid
23. zoom

**Comment by SethStormR** [comment]
That's quite a list ;)
But I should get them done for next week update.

**Comment by dirn-intg** [comment]
> That's quite a list ;) But I should get them done for next week update.

No problem, take your time :)

**Comment by SethStormR** [comment]
All is done except number one on the list - can you check if it goes under another name?

**Comment by dirn-intg** [comment]
> All is done except number one on the list - can you check if it goes under another name?

The app name is CoolerControl. Here's the project link
https://gitlab.com/coolercontrol/coolercontrol

**Comment by SethStormR** [comment]
Okay. I think I got it right. I'll upload version 1.1 to githhub so you can give it as test.

**Comment by dirn-intg** [comment]
> Okay. I think I got it right. I'll upload version 1.1 to githhub so you can give it as test.

Sure, I will check on it tonight.

**Comment by dirn-intg** [comment]
The rest is okay, only icons below not mapped to the apps
1. World of Padman
2. Zoom
3. Virtual Box
4. Ventoy

**Comment by SethStormR** [comment]
Can you please check /usr/share/applications and open the .desktop files with an editor and look for **icon=**. Post back what the names are for the missing icons.
I guess World of Padman and Zoom is flatpak, but I have already added flatpak names to them?

**Comment by dirn-intg** [comment]
World of Padman
`Icon=worldofpadman.svg`

Zoom
`Icon=Zoom`

Virtual Box
`Icon=virtualbox`

Ventoy
`Icon=ventoy`

**Comment by SethStormR** [comment]
The only one missing in the icon theme pack was World of Padman. Have you tried resetting the icons if you  (as I understand) had manually added icons to each of the missing apps.

**Comment by dirn-intg** [comment]
> The only one missing in the icon theme pack was World of Padman. Have you tried resetting the icons if you (as I understand) had manually added icons to each of the missing apps.

You're right. I forgot to reset these 3 icons. It's working now.
Only World of Padman is missing.

**Comment by SethStormR** [comment]
I have updated the icon theme, so World of Padman is included.
