### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by dirn-intg** [SethStormR/GreyStone#2]
Here's another list
1. amd
2. AppImageLauncher
3. applications-education-miscellaneous
4. calf
5. cmake
6. dart
7. hp_logo
8. hp-logo
9. intel
10. java
11. network-wired
12. qt
13. qtassistant
14. QtAV
15. qtdbusviewer
16. qtdesigner
17. qtractor
18. qv4l2
19. uget
20. warsow
21. xterm

**Comment by SethStormR** [comment]
List of missing todo list. I'll remove the item(s) on hte list when done.


AppImageLauncher
applications-education-miscellaneous
calf
cmake
dart
hp_logo
hp-logo
intel
java
qt
qtassistant
QtAV
qtdbusviewer
qtdesigner
qtractor
uget
warsow

**Comment by SethStormR** [comment]
All done.

**Comment by dirn-intg** [comment]
Tested. Closing the issue.
