### ISSUE TITLE
Icons suggestions

### ISSUE THREAD

**Issue by Mr-Bajs** [SethStormR/GreyStone#4]
A very nice icon set I must say. Shows a lot of promise.

I suppose the the colorised icons in the set are a progress to replace with what I assume are the GreyStone style.

Though the following apps would be very nice if they also where stylised into GreyStone:

Librewolf
FreeTube
KeepassXC
Lutris
Heroic Games Launcher
Mullvad VPN
Mullvad Browser

**Comment by SethStormR** [comment]
Done and uploaded to github version 1.8.
