### ISSUE TITLE
Protonmail desktop app.

### ISSUE THREAD

**Issue by Mr-Bajs** [SethStormR/GreyStone#5]
Icon for the Protonmail desktop application would be great. The Linux version are only in beta and uses a slight modified icon though.

The apps
https://proton.me/mail/download

Link to the icons
https://github.com/ProtonMail/WebClients/tree/main/applications/inbox-desktop/assets/icons

**Comment by SethStormR** [comment]
Hello,

I'll add it soon.

**Comment by SethStormR** [comment]
I have uploaded a new version to github with ProtonMail, ProtonMail Bridge and Proton Drive.
